apiVersion: v1 
kind: Deployment
metadata:
  name: nginx-green
  # these are replicaset labels.
  labels:
    project: roboshop
    purpose: rs-demo 
    tier: frontend
    component: frontend
    version: green
spec:
  replicas: 3
  selector:
    # Using these labels replicaset selects the pod.
    matchLabels:
      project: roboshop
      purpose: rs-demo 
      tier: frontend
      component: frontend
      version: green
  # This is pod definition,  pod is subset of replicaset
  template:
  metadata: 
    labels:
      project: roboshop
      purpose: rs-demo 
      tier: frontend
      component: frontend
      version: green
    spec:
      containers:
      - name: nginx-green
        image: lokeshlh/blue-green:0.0.2